apiVersion: apps/v1
kind: Deployment
metadata:
  name: crispy-octo-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: crispy-octo-app
  template:
    metadata:
      labels:
        app: crispy-octo-app
    spec:
      containers:
      - name: crispy-octo-app
        image: tarik45/crispy-octo-app:latest
        ports:
        - containerPort: 3000
        env:
        - name: EMAIL_PORT
          value: "587"
        - name: EMAIL_USERNAME
          value: jet@gmail.com
        - name: EMAIL_PASSWORD
          value: fr1226
        - name: REDIS_URL
          value: "redis://redis.host:6379/"
        - name: EMAIL_FROM
          value: test@hotmail.fr
        - name: MYSQL_DATABASE
          value: crispy_octo_development
        - name: MYSQL_USER
          value: crispy
        - name: MYSQL_PASSWORD
          value: test
        - name: DATABASE_URL
          value: "mysql2://${MYSQL_USER}:${MYSQL_PASSWORD}@mysql.host/${MYSQL_DATABASE}?pool=5"
        - name: crispy-octo-worker
          image: tarik45/crispy-octo-worker:latest
        - name: mysql
          image: mysql:5.7
        - name: redis
          image: redis:alpine
