version: '3'
services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: your_mysql_root_password
      MYSQL_DATABASE: your_mysql_database
      MYSQL_USER: your_mysql_username
      MYSQL_PASSWORD: your_mysql_password
  redis:
    image: redis:alpine