version: '3'
services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    links:
      - "db:mysql.host"
      - "redis:redis.host"
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL
      - EMAIL_PORT
      - EMAIL_USERNAME
      - EMAIL_PASSWORD
    depends_on:
      - db
      - redis
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
        - "._mysql_data_dir/:/var/lib/mysql"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_ROOT_PASSWORD=your_mysql_root_password
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
  redis:
    image: redis:alpine